### PR TITLE
Rename water budget data

### PR DESCRIPTION
**Pull request by hcorson-dosch-usgs**
* Downstream changes resulting from Sam's change to filenames [here](https://github.com/USGS-R/delaware-model-prep/pull/94) -- `interpolated_daily_diversions.csv` renamed to `interpolated_daily_reservoir_water_budget_components.csv`

### CODE REVIEW

**Comment by hcorson-dosch-usgs** [comment]
Note - already pushed updated file and metadata to SB and deleted old file from SB

**Comment by hcorson-dosch-usgs** [comment]
WAIT - I messed up the name b/c I forgot to add the `reservoir_` prefix 🤦‍♀️ -- will add now

**Comment by limnoliver** [comment]
I could have made this easy on you and followed the naming conventions I recommended!

**Comment by hcorson-dosch-usgs** [comment]
No worries! Fixed now

**Review by limnoliver — APPROVED** [review]

**Pull request merged**
